### ISSUE TITLE
Getting exception when opening a java file

### ISSUE THREAD

**Issue by ronakg** [neoclide/coc-java#10]
I'm getting the following exception when I open a `.java` file. 

```
## versions

vim version: NVIM v0.3.4
node version: v10.15.3
coc.nvim version: 0.0.59
term: iTerm.app
platform: darwin

## Error messages

## Output channel: java
[Error  - 2:32:56 PM] Mar 11, 2019 2:32:56 PM An internal error occurred during: "Initialize Workspace".
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.apache.maven.model.Dependency.getManagementKey(Dependency.java:612)
	at org.apache.maven.model.merge.MavenModelMerger.getDependencyKey(MavenModelMerger.java:629)
	at org.apache.maven.model.merge.ModelMerger.mergeDependencyManagement_Dependencies(ModelMerger.java:1472)
	at org.apache.maven.model.merge.ModelMerger.mergeDependencyManagement(ModelMerger.java:1452)
	at org.apache.maven.model.merge.ModelMerger.mergeModelBase_DependencyManagement(ModelMerger.java:682)
	at org.apache.maven.model.merge.ModelMerger.mergeModelBase(ModelMerger.java:536)
	at org.apache.maven.model.merge.ModelMerger.mergeModel(ModelMerger.java:126)
	at org.apache.maven.model.merge.MavenModelMerger.mergeModel(MavenModelMerger.java:76)
	at org.apache.maven.model.merge.ModelMerger.merge(ModelMerger.java:121)
	at org.apache.maven.model.inheritance.DefaultInheritanceAssembler.assembleModelInheritance(DefaultInheritanceAssembler.java:67)
	at org.apache.maven.model.building.DefaultModelBuilder.assembleInheritance(DefaultModelBuilder.java:724)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:380)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:158)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:116)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:628)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$2(ProjectRegistryManager.java:698)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$$Lambda$63/409249940.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.execute(ProjectRegistryManager.java:958)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readMavenProjectFacade(ProjectRegistryManager.java:694)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:396)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:349)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:296)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:259)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
```

**Comment by chemzqm** [comment]
Looks like you need configure `jdt.ls.vmargs` in settings.json to a higher value.

**Comment by ronakg** [comment]
The `coc-settings.json` file is empty right now. Do you know what value should I use for `java.jdt.ls.vmargs`?

**Comment by chemzqm** [comment]
@ronakg I don't use java, checkout https://github.com/eclipse/eclipse.jdt.ls#feedback

**Comment by JayceCao** [comment]
> The `coc-settings.json` file is empty right now. Do you know what value should I use for `java.jdt.ls.vmargs`?

just like this: `-noverify -Xmx2G -XX:+UseG1GC -XX:+UseStringDeduplication`. The value of `-Xmx` is the memory size.

**Comment by chemzqm** [comment]
Try to increase the memory size by configure `java.jdt.ls.vmargs`
