### ISSUE TITLE
Completing functions can be slow

### ISSUE THREAD

**Issue by ludwj61** [neoclide/coc-java#129]
I don't know exactly when this started happening, but currently when selecting and confirming some completion options, there is a slightly to very noticeable delay.

For example, if I have some map like ``Map<Integer, Integer> m = new TreeMap<>();`` and I do trigger autocomplete for ``m.entrySet()`` I have seen a second or so delay when I feel like it should be essentially instant.

Basically, it seems this delay occurs whenever a completion has that snippet-like behavior where parenthesis are automatically created and your cursor is put in between them.

I have the latest release of coc, this plugin, and I'm on nightly neovim on arch.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Could be caused by your `sel` command is slow, will improve it.

**Comment by ludwj61** [comment]
@chemzqm Thanks, I will try with minimal vimrc. 

But can you explain what you mean by my ``sel`` command being slow? Should I set it to something besides the default, which is ``inclusive``?

**Comment by chemzqm** [comment]
It's external command which can be quite shlow.

**Comment by Frederick888** [comment]
Completions have also been slower than usual recently for me. Not sure what the reason is, but I noticed that now I often have to wait for ~3s before diagnostics about syntax error go away even I've already finished typing, and before they disappear no new completions show up.

<img width="530" alt="Screen Shot 2020-11-23 at 12 04 34 pm" src="https://user-images.githubusercontent.com/4507647/100188324-11eaa400-2f3e-11eb-977e-d7dc2fadd618.png">

If this is purely a performance issue, I wonder if it's possible to only refresh diagnostics on save, although I understand this is not how it's supposed to work...

**Comment by ludwj61** [comment]
@chemzqm finally got around to testing with minimal vimrc. 
With only ``Plug 'neoclide/coc.nvim', {'branch': 'release'}`` in addition to the "default" config from the coc.nvim readme I still get the same issue.
<details>

```vimscript
" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Remap <C-f> and <C-b> for scroll float windows/popups.
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" Use CTRL-S for selections ranges.
" Requires 'textDocument/selectionRange' support of language server.
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
```

</details>

If I type something like ``new Treemap`` and trigger completion and then just tap ``<CR>`` so to trigger something like ``new Treemap<>()``(no scrolling the completion list required), there is a consistant 1 or 2 second delay before the library is imported and the action completes.

**Comment by chemzqm** [comment]
Try upgrade coc.nvim

**Comment by ludwj61** [comment]
@chemzqm Thanks, but I am already using the latest version. I even tried building from master.

**Comment by chemzqm** [comment]
Try profile your vim, `:h :profile`

**Comment by ludwj61** [comment]
@chemzqm I was expecting to see some big delay on ``coc#_do_complete()`` but that was not the case.

Here is the summary:
<details>

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   33   0.009260             <SNR>46_Highlight_Matching_Pair()
   66   0.008158   0.001042  <SNR>33_Autocmd()
   67   0.007187   0.001480  coc#rpc#notify()
   67   0.005082   0.004596  <SNR>36_notify()
    1   0.001327   0.000061  provider#clipboard#Call()
    1   0.001265             3()
    1   0.001036   0.000797  coc#_complete()
   67   0.000625             coc#rpc#ready()
   24   0.000496             coc#util#do_autocmd()
   67   0.000487             coc#client#get_channel()
    1   0.000409   0.000278  GetJavaIndent()
    1   0.000196   0.000027  coc#start()
    2   0.000174   0.000139  coc#float#nvim_refresh_scrollbar()
    2   0.000143   0.000104  coc#highlight#clear_highlight()
    2   0.000139             coc#highlight#clear_match_group()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   33              0.009260  <SNR>46_Highlight_Matching_Pair()
   67   0.005082   0.004596  <SNR>36_notify()
   67   0.007187   0.001480  coc#rpc#notify()
    1              0.001265  3()
   66   0.008158   0.001042  <SNR>33_Autocmd()
    1   0.001036   0.000797  coc#_complete()
   67              0.000625  coc#rpc#ready()
   24              0.000496  coc#util#do_autocmd()
   67              0.000487  coc#client#get_channel()
    1   0.000409   0.000278  GetJavaIndent()
    2              0.000139  coc#highlight#clear_match_group()
    2   0.000174   0.000139  coc#float#nvim_refresh_scrollbar()
    3              0.000131  coc#float#check_related()
    3              0.000131  SkipJavaBlanksAndComments()
    1              0.000126  coc#_select_confirm()
```

</details>

Maybe I am missing something but I do no see the profiler showing the delay. 
Since you still can't reproduce this, I am curious, are you using the latest version of jdtls?

**Comment by chemzqm** [comment]
It should not a problem of jdtls.

**Comment by chemzqm** [comment]
Maybe your jdtls get blocked on completion resolve, checkout the output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ludwj61** [comment]
I think I did find relevant errors. These sorts of errors about timeouts when reading documentation occurs when triggering completion whether or not I actually scroll the completion menu to show documentation, however. It at least seems to show the slowdown I am experiencing.

<details>

```
[Trace - 10:58:58 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Dec 2, 2020, 10:58:58 PM Unable to read documentation\nnull\njava.util.concurrent.TimeoutException\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\n\tat com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)\n\tat org.eclipse.jdt.ls.core.internal.handlers.CompletionResolveHandler.resolve(CompletionResolveHandler.java:162)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:536)\n\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\n\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\n"
}


[Error  - 10:58:58 PM] Dec 2, 2020, 10:58:58 PM Unable to read documentation
null
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionResolveHandler.resolve(CompletionResolveHandler.java:162)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:536)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Trace - 10:58:58 PM] Received response 'completionItem/resolve - (6)' in 637ms.
Result: {
    "label": "Random()",
    "kind": 4,
    "detail": "java.util.Random.Random()",
    "sortText": "999998843",
    "insertText": "Random",
    "insertTextFormat": 2,
    "textEdit": {
        "range": {
            "start": {
                "line": 8,
                "character": 31
            },
            "end": {
                "line": 8,
                "character": 34
            }
        },
        "newText": "Random()"
    },
    "additionalTextEdits": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 2,
                    "character": 0
                }
            },
            "newText": "import java.util.Random;\n"
        }
    ]
}
```
</details>

**Comment by chemzqm** [comment]
> [Trace - 10:58:58 PM] Received response 'completionItem/resolve - (6)' in 637ms.

So it's problem of your jdt.ls

**Comment by ludwj61** [comment]
@chemzqm I see, thanks. However, I noticed that I don't get this issue with other programs using the same LSP. For example, this does not happen even when using neovim's built-in LSP with jdt.ls. 
Is there any way coc can be downloading the wrong version or something?

**Comment by chemzqm** [comment]
Maybe neovim's built-in LSP doesnt invoke complete resolve, you can configure the path of jdt.ls

**Comment by ludwj61** [comment]
FWIW I opened an issue about it on jdt.ls repo and there is now a pull request that will hopefully fix this issue https://github.com/eclipse/eclipse.jdt.ls/pull/1625

**Comment by ludwj61** [comment]
Just to follow up, how does this plug in decide what version of jdt.ls to download? Does it use the snapshot or milestone builds uploaded on the eclipse website? I ask as I am not sure if the fix I linked previously is being used or not when I do ``CocInstall coc-java``.

**Comment by ludwj61** [comment]
I have found that this issue persists only if the first completion item is not highlighted is selected.
To clarify, using the following config, which is on the coc.nvim readme, causes the lag issue I've been experiencing:
```vim
" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
Highlighting the first completion result before pressing <CR> results in no lag.

**Comment by chemzqm** [comment]
It's problem of your jdt.ls.

**Comment by yimingwangdell** [comment]
@jacksonludwig same issue, after switch to native nvim-jdtls, everything goes well.
