### ISSUE TITLE
ERROR (pid:21591) [language-client-client] - connection error: Error: write EPIPE

### ISSUE THREAD

**Issue by MuizU** [neoclide/coc-java#135]
When I open a java file and execute :CocInfo I get the following result

`2020-12-22T11:05:49.294 INFO (pid:21591) [services] - registered service "languageserver.bash"
2020-12-22T11:05:49.529 INFO (pid:21591) [coc-java] - Using java from /usr/lib/jvm/java-11-openjdk, version: 11
2020-12-22T11:05:49.713 INFO (pid:21591) [coc-java] - JDT Language Server starting at /mnt/c/Users/muizu/OneDrive/Documents/IIT/Level 6/Concurrent programming/Senthuran Cwk/concurrent-printing-system-demo
2020-12-22T11:05:49.714 INFO (pid:21591) [services] - registered service "java"
2020-12-22T11:05:49.729 INFO (pid:21591) [plugin] - coc.nvim 0.0.80-7642d233d6 initialized with node: v15.4.0 after 909ms
2020-12-22T11:05:49.736 INFO (pid:21591) [language-client-index] - Language server "java" started with 21618
2020-12-22T11:05:49.774 ERROR (pid:21591) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:162:15)
    at writeGeneric (node:internal/stream_base_commons:153:3)
    at Socket._writeGeneric (node:net:774:11)
    at Socket._write (node:net:786:8)
    at writeOrBuffer (node:internal/streams/writable:388:12)
    at Socket.Writable.write (node:internal/streams/writable:333:10)
    at StreamMessageWriter.write (/home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:18351:27)
    at /home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:17499:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:17489:26)
    at Object.initialize (/home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:80356:44)
    at LanguageClient.doInitialize (/home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:82494:27)
    at LanguageClient.initialize (/home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:82490:25)
    at /home/muizu/.config/nvim/autoload/plugged/coc.nvim/build/index.js:82413:25 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-12-22T11:05:51.463 INFO (pid:21591) [attach] - receive notification: showInfo []`

**Comment by chemzqm** [comment]
Looks like your local jdt.ls is broken, you can download it yourself and configure coc-java to use it.

**Comment by MuizU** [comment]
> Looks like your local jdt.ls is broken, you can download it yourself and configure coc-java to use it.

I Installed it using arch and I added `java.jdt.ls.home` in coc-settings.json to point to the location but I still get an error
![image](https://user-images.githubusercontent.com/35157872/102882535-826cde00-4474-11eb-9662-c96fd9b3296f.png)

**Comment by chemzqm** [comment]
Looks like it can't use java-11-openjdk, you need check log of language server.
