### ISSUE TITLE
ERROR (pid:96095) [server] - uncaughtException Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by SirNoob97** [neoclide/coc-java#136]
hi i have a problem scanning my project.

I have a postgres container with the volume to the data folder

    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

so when trying to scan the contents of that folder when starting the jdt, the command: CocOpenLog shows me this exception

    2020-12-22T20:14:51.605 ERROR (pid:96095) [server] - uncaughtException Error: Header must provide a Content-Length property.
      at StreamMessageReader.onData (/absolute/path/to/vim/.vim/plugged/coc.nvim/build/index.js:18074:27)
      at Socket.<anonymous> (/absolute/paht/to/vim/.vim/plugged/coc.nvim/build/index.js:18059:18)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

the command: CocCommand java.open.serverLog showed me this

    !ENTRY org.eclipse.jdt.ls.core 4 0 2020-12-22 20:08:28.756
    !MESSAGE Initialization failed
    !STACK 1
    org.eclipse.core.runtime.CoreException: Failed to scan /absolute/paht/to/my/workspace
      at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:140)
        at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.applies(GradleProjectImporter.java:106)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:114)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:104)
        at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:195)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
      Caused by: java.nio.file.AccessDeniedException: /absolute/paht/to/postgresql/data
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scanDir(BasicFileDetector.java:174)
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:138)
        ... 6 more
        !SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2020-12-22 20:08:28.757
        !MESSAGE Failed to scan /absolute/paht/to/my/workspace
        !STACK 0
        java.nio.file.AccessDeniedException: /absolute/paht/to/postgresql/data
          at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scanDir(BasicFileDetector.java:174)
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:138)
        at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.applies(GradleProjectImporter.java:106)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:114)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:104)
        at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:195)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Is there a way to exclude directories or files from project scan? or any other solution?

I already tried to remove the content of .config/coc but it doesn't work now, it just shows me this and the command: CocOpenLog doesn't show the first exception

    [coc.nvim] JDT language server error Could not scan /path/to/my/project

:CocCommand java.open.serverLog this command shows me the same exception

the only thing that works for me is using vim with sudo since the folder belongs to the root user, but I don't want to do that

sorry for my bad english and thanks for helping me

**Comment by chemzqm** [comment]
It's problem of jdt.ls

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

From 1.14.0, coc-java uses bundled jdt.ls
