### ISSUE TITLE
jdtls 1.1.1 fails to start

### ISSUE THREAD

**Issue by radimsuckr** [neoclide/coc-java#157]
Hi,

I use [jdtls from AUR](https://aur.archlinux.org/packages/jdtls/) on Arch Linux with OpenJDK 15.0.2.u7 and it just got updated to 1.1.1 and this version fails to start with following log output:

```
2021-05-10T11:04:36.857 INFO (pid:47663) [coc-java] - Using java from /usr/lib/jvm/default, version: 15
2021-05-10T11:04:36.863 INFO (pid:47663) [plugin] - coc.nvim 0.0.80-46353b786b initialized with node: v16.1.0 after 210ms
2021-05-10T11:04:36.879 INFO (pid:47663) [coc-java] - JDT Language Server starting at /home/grelek/projects/java-stream-induction
2021-05-10T11:04:36.880 INFO (pid:47663) [services] - registered service "java"
2021-05-10T11:04:36.885 INFO (pid:47663) [language-client-index] - Language server "java" started with 47695
2021-05-10T11:04:38.460 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.461 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.463 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.471 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.666 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.667 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.756 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.756 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.757 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.791 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.791 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.793 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.958 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.958 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.960 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.965 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.966 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.966 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.989 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.992 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:38.993 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:39.556 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:39.557 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:39.571 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:04:39.571 ERROR (pid:47663) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at jw.onData (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2751)
    at Socket.<anonymous> (/home/grelek/.cache/nvim/plugged/coc.nvim/build/index.js:25:2488)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
2021-05-10T11:05:02.339 INFO (pid:47663) [attach] - receive notification: openLog []
```

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

For 1.14.0, coc-java use bundled jdt.ls to avoid such kind of bugs.
