### ISSUE TITLE
I get this error when i install coc-java

### ISSUE THREAD

**Issue by arleyvelascoo** [neoclide/coc-java#167]
`[coc.nvim]: UnhandledRejection: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:783:11)
    at Socket._write (net.js:795:8)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:367:5)
    at Socket.Writable.write (_stream_writable.js:307:12)
    at /home/arley/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/arley/.vim/plugged/coc.nvim/build/index.js:33:3028)
`
Someone can help me?
![image](https://user-images.githubusercontent.com/42453781/124393914-72a34180-dcc2-11eb-8ab5-1e99861d3e10.png)

**Comment by chemzqm** [comment]
Avoid use `$SERVER_PORT` env.
