### ISSUE TITLE
Packages from my dependencies are not being imported

### ISSUE THREAD

**Issue by lucaspeixotot** [neoclide/coc-java#177]
All the packages from my dependencies are not being imported, for example, always that a package initiates with "org" the import cannot be done.

![image](https://user-images.githubusercontent.com/11475476/134940712-adfb306a-522a-48c1-b6d4-04912cfe964c.png)

Here is my CocConfig:
```
{
    "codeLens.enable": true,
    "java.referencesCodeLens.enabled": true,
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-11",
        "path": "/usr/lib/jvm/java-11-openjdk-amd64",
      },
    ],
    "java.trace.server": "verbose",
    "java.format.enabled": true,
    "java.import.maven.enabled": true,
    "java.maven.downloadSources": true,
}
```

Here is my server log:

```
!SESSION 2021-09-27 12:36:11.288 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.11
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /home/lucas/.config/coc/extensions/coc-java-data/jdt_ws_e331f4a87af6b19bcb396a20cf9b0e05

!ENTRY org.gradle.toolingapi 4 0 2021-09-27 12:36:12.930
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.util.zip.ZipException: Exception in opening zip file: /home/lucas/.config/coc/extensions/coc-java-data/server/plugins/org.gradle.toolingapi_7.0.0.v20210616-0346-s.jar
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:273)
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.doOpen(ZipBundleFile.java:51)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.open(CloseableBundleFile.java:135)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.lockOpen(CloseableBundleFile.java:77)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.getEntry(CloseableBundleFile.java:274)
	at org.eclipse.osgi.storage.BundleInfo$Generation.getEntry(BundleInfo.java:423)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getEntry(EquinoxBundle.java:694)
	at org.eclipse.core.internal.registry.osgi.EclipseBundleListener.getExtensionURL(EclipseBundleListener.java:122)
	at org.eclipse.core.internal.registry.osgi.EclipseBundleListener.addBundle(EclipseBundleListener.java:165)
	at org.eclipse.core.internal.registry.osgi.EclipseBundleListener.processBundles(EclipseBundleListener.java:94)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.onStart(RegistryStrategyOSGI.java:243)
	at org.eclipse.core.internal.registry.ExtensionRegistry.<init>(ExtensionRegistry.java:740)
	at org.eclipse.core.runtime.RegistryFactory.createRegistry(RegistryFactory.java:61)
	at org.eclipse.core.internal.registry.osgi.Activator.startRegistry(Activator.java:143)
	at org.eclipse.core.internal.registry.osgi.Activator.start(Activator.java:60)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.lambda$2(BundleContextImpl.java:808)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:802)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:759)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1019)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:404)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:384)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:463)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.core.internal.content.ContentTypeManager.<clinit>(ContentTypeManager.java:41)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.felix.scr.impl.inject.internal.ComponentConstructorImpl.newInstance(ComponentConstructorImpl.java:312)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:286)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:776)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.addingBundle(AbstractExtender.java:139)
	at org.apache.felix.scr.impl.AbstractExtender.addingBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:935)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:206)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
	at org.eclipse.osgi.container.Module.start(Module.java:486)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1581)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1476)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1483)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1288)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1251)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:849)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:264)
	... 74 more

!ENTRY org.eclipse.core.resources 2 10035 2021-09-27 12:36:13.131
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.086
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.512
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.625
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.635
!MESSAGE Initializing Java Language Server 1.5.0.202109270336

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.694
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.695
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveSourceAttachment, java.project.addToSourcePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.703
!MESSAGE Starting org.eclipse.m2e.core

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:14.707
!MESSAGE Started org.eclipse.m2e.core 4ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:15.382
!MESSAGE ProjectRegistryRefreshJob finished 675ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:15.382
!MESSAGE Starting org.eclipse.buildship.core

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:15.477
!MESSAGE Started org.eclipse.buildship.core 95ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:15.531
!MESSAGE LoadingGradleVersionJob finished 54ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:15.600
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.768
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.870
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.931
!MESSAGE Workspace initialized in 1397ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.935
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.959
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.970
!MESSAGE >> New configuration: {java={enabled=true, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={checkProjectSettingsExclusions=true, updateBuildConfiguration=interactive, runtimes=[{name=JavaSE-11, path=/usr/lib/jvm/java-11-openjdk-amd64}]}, trace={server=verbose}, import={gradle={enabled=true, wrapper={enabled=true}, offline={enabled=false}}, maven={enabled=true}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, maven={updateSnapshots=false, downloadSources=true}, referencesCodeLens={enabled=true}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, comments={enabled=true}, onType={enabled=true, fixComment={enabled=true}}}, saveActions={organizeImports=false}, project={referencedLibraries=[lib/**/*.jar], resourceFilters=[node_modules, .git]}, autobuild={enabled=true}, maxConcurrentBuilds=1.0, completion={maxResults=0.0, enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], filteredTypes=[java.awt.*, com.sun.*], importOrder=[java, javax, com, org]}, progressReports={enabled=true}, foldingRange={enabled=true}, codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false}, useBlocks=false, generateComments=false, toString={template=${object.className} [${member.name()}=${member.value}, ${otherMembers}], codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true, limitElements=0.0}}, selectionRange={enabled=true}, sources={organizeImports={starThreshold=99.0, staticStarThreshold=99.0}}, templates={fileHeader=[], typeComment=[]}, references={includeAccessors=true}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:16.971
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:21.116
!MESSAGE >> textDocument/semanticTokens/full

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:21.127
!MESSAGE >> document/codeLens

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:21.139
!MESSAGE >> document/definition

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:21.287
!MESSAGE >> document/definition

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:22.838
!MESSAGE Reconciled 1. Took 0 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:22.859
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:22.867
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:24.488
!MESSAGE begin problem for /App.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:24.489
!MESSAGE 0 problems reported for /App.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:24.507
!MESSAGE Validated 1. Took 1571 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:24.519
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:24.998
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:25.003
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:36:25.008
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.358
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.558
!MESSAGE >> document/codeLens

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.830
!MESSAGE Reconciled 1. Took 0 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.853
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.856
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.861
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.866
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.890
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.901
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:45.914
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:46.717
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:46.726
!MESSAGE >> codeLens/resolve

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:46.785
!MESSAGE begin problem for /UserPayloads.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:46.785
!MESSAGE 0 problems reported for /UserPayloads.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:47.196
!MESSAGE begin problem for /App.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:47.196
!MESSAGE 0 problems reported for /App.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:47.199
!MESSAGE Validated 2. Took 968 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:47.359
!MESSAGE >> textDocument/semanticTokens/full

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-09-27 12:38:48.004
!MESSAGE >> codeLens/resolve

```

**Comment by igbanam** [comment]
Did you find a solution to this?

**Comment by lucaspeixotot** [comment]
Yes I found one. I just stopped to use this plugin and now everything is working kkkkk. I'm using neovim with nvim lsp and jdtls and I'm good now. Good lucky with coc.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
