### ISSUE TITLE
JDK returns error code 13

### ISSUE THREAD

**Issue by HarryWangATX** [neoclide/coc-java#208]
When initiating jdt, logs show my java exited with code 13. What is the reason for this error?

**Comment by zl03jsj** [comment]
I got the same error.
there are `CocCommand workspace.show java' outputs:
```
[Error - 13:57:41] /usr/local/opt/jdk-11.0.16.1.jdk/Contents/Home/bin/java exited with code: 13
[Error - 13:57:42] Client Language Support for Java: connection to server is erroring. Shutting down server.
[Error - 13:57:42] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: 2
    at zc.shutdown (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:248:8842)
    at zc.stop (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:248:8637)
    at zc.stop (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:252:2975)
    at zc.handleConnectionError (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:248:11872)
    at e (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:248:10562)
    at /Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:243:90852
    at GD.invoke (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Su.fire (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at st (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:24:6575)
    at GD.invoke (/Users/zl/.local/share/nvim/plugged/coc.nvim/build/index.js:23:14460)
[Info  - 13:57:42] Connection to server got closed. Server will restart.
[Error - 13:57:42] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 13:57:42] Language Support for Java client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 13:57:42] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 13:57:42] Sending request 'initialize - (0)'.
```
and error messages:
```
[coc.nvim] Client Language Support for Java: connection to server is erroring. Shutting down server.
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Language Support for Java client: couldn't create connection to server.
[coc.nvim]: UnhandledRejection: Pending response rejected since connection got disposed
[coc.nvim] Client Language Support for Java: connection to server is erroring. Shutting down server.
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Language Support for Java client: couldn't create connection to server.
[coc.nvim]: UnhandledRejection: Pending response rejected since connection got disposed
[coc.nvim] Client Language Support for Java: connection to server is erroring. Shutting down server.
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Language Support for Java client: couldn't create connection to server.
[coc.nvim] Restarting server failed
[coc.nvim] Client Language Support for Java: connection to server is erroring. Shutting down server.
[coc.nvim] The "java" server crashed 4 times in the last 3 minutes. The server will not be restarted.
[coc.nvim] Connection to server got closed. Server will not be restarted.
[coc.nvim] Pending response rejected since connection got disposed
[coc.nvim] Language Support for Java client: couldn't create connection to server.
[coc.nvim] Restarting server failed
```

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.

Checkout https://github.com/neoclide/coc-java/blob/master/Readme.md#setting-the-jdk for configure java used by jdt.ls
