### ISSUE TITLE
[coc.nvim]TypeError:Cannot read properties of null (reading 'hasOwnProperty') when use coc-java

### ISSUE THREAD

**Issue by FighterArcher** [neoclide/coc-java#217]
### Env
vim8 + coc.nvim + coc-java + node16

**Comment by grindarius** [comment]
having the same error using node latest lts with neovim 0.7.2 + kitty terminal on Linux Mint 20.3 una (Xfce)

**Comment by chemzqm** [comment]
Please provide the log from `:CocInfo`

**Comment by grindarius** [comment]
> Please provide the log from `:CocInfo`

```
## versions

vim version: NVIM v0.7.2
node version: v16.17.0
coc.nvim version: 0.0.82-96700049 2022-08-21 17:45:20 +0800
coc.nvim directory: /home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2022-08-24T16:07:24.750 INFO (pid:41922) [configurations] - Add folder configuration from cwd: /home/grindarius/coding-projects/nmea_checksum/.vim/coc-settings.json
2022-08-24T16:07:24.752 INFO (pid:41922) [configurations] - Change folder configuration from cwd to: /home/grindarius/coding-projects/nmea_checksum/.vim/coc-settings.json
2022-08-24T16:07:24.991 ERROR (pid:41922) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-08-24T16:07:24.991 ERROR (pid:41922) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-08-24T16:07:25.190 INFO (pid:41922) [plugin] - coc.nvim initialized with node: v16.17.0 after 247ms
2022-08-24T16:07:25.226 INFO (pid:41922) [core-watchman] - watchman watching project: /home/grindarius/coding-projects/nmea_checksum
2022-08-24T16:07:25.503 INFO (pid:41922) [coc-java] - Using java from /usr/lib/jvm/java-11-openjdk-amd64, version: 11
2022-08-24T16:07:25.647 INFO (pid:41922) [extension:coc-java] - Starting Java server with: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf-8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /home/grindarius/.config/coc/extensions/coc-java-data/server/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /home/grindarius/.config/coc/extensions/coc-java-data/server/config_linux -data /home/grindarius/.config/coc/extensions/coc-java-data/jdt_ws_a88affceedebbe6038a699ee3798ea38
2022-08-24T16:07:25.654 INFO (pid:41922) [coc-java] - JDT Language Server starting at /home/grindarius/coding-projects/nmea_checksum
2022-08-24T16:07:25.656 INFO (pid:41922) [services] - registered service "java"
2022-08-24T16:07:25.701 INFO (pid:41922) [language-client-index] - Language server "java" started with 41976
2022-08-24T16:07:27.733 WARN (pid:41922) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-24T16:07:28.028 WARN (pid:41922) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-24T16:07:29.829 WARN (pid:41922) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-24T16:07:30.616 WARN (pid:41922) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-24T16:07:35.406 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
    at async Fx.completeSources (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:31874)
    at async Fx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:31423)
    at async Nne.startCompletion (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:46488)
    at async Nne.triggerCompletion (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:48922)
    at async Nne.onTextChangedI (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:47924)
2022-08-24T16:07:35.407 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:36.057 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
    at async Fx.completeSources (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:31874)
    at async Fx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:31423)
    at async Nne.startCompletion (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:46488)
    at async Nne.triggerCompletion (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:48922)
    at async Nne.onTextChangedI (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:47837)
2022-08-24T16:07:36.057 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:37.640 WARN (pid:41922) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-24T16:07:38.379 WARN (pid:41922) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-24T16:07:38.818 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
2022-08-24T16:07:38.818 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:38.854 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
2022-08-24T16:07:38.854 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:40.242 INFO (pid:41922) [attach] - receive notification: highlight []
2022-08-24T16:07:40.605 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
2022-08-24T16:07:40.605 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:40.607 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
2022-08-24T16:07:40.607 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:40.611 ERROR (pid:41922) [node-client] - TypeError: Cannot read properties of null (reading 'hasOwnProperty') Error
    at OH.echoError (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:26:1869)
    at Fx.completeSource (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:32878)
    at async Promise.all (index 0)
    at async Fx.completeSources (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:31874)
    at async Fx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:31423)
    at async Nne.startCompletion (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:46488)
    at async Nne.triggerCompletion (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:48922)
    at async Nne.onTextChangedI (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:269:47837)
2022-08-24T16:07:40.611 ERROR (pid:41922) [completion-complete] - Complete error: java TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/grindarius/.config/coc/extensions/node_modules/coc-java/lib/index.js:261:37
    at async Dx.doComplete (/home/grindarius/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:266:2513)
2022-08-24T16:07:43.817 INFO (pid:41922) [attach] - receive notification: showInfo []
```

I am using neovim 0.7.2 with latest version of coc-java with eclipse-jdt 1.9.0. The error disappears when I switched to using `openjdk-17`

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
