### ISSUE TITLE
Got [coc.nvim]: UnhandledRejection: Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by tanathap** [neoclide/coc-java#224]
I found the following error after installing coc-java.
```
[coc.nvim]: UnhandledRejection: Pending response rejected since connection got disposed
Error: Pending response rejected since connection got disposed
    at Object.dispose (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:54:4562)
    at Object.dispose (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:219:85794)
    at jf.handleConnectionClosed (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:224:10872)
    at jf.handleConnectionClosed (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:228:3578)
    at t (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:224:10524)
    at mq.invoke (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:27:14460)
    at fg.fire (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:27:15230)
    at Re (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:28:6501)
    at mq.invoke (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:27:14460)
    at fg.fire (/home/tanathep/.local/share/nvim/plugged/coc.nvim/build/index.js:27:15230)
```
and I have no clue how to solve this problem. Someone pls help.

**Comment by tanathap** [comment]
This is nvim on wsl ubuntu20.04.5 LTS

**Comment by chemzqm** [comment]
See https://github.com/neoclide/coc-java/issues/220#issuecomment-1229484709

**Comment by WJ-Prajumsook** [comment]
I got same error on MacOS, java 17.
In my case, in the log I found an error about missing coc-java-lombok and efter install coc-java-lombok it works fine now.

**Comment by kkopczynski-roq** [comment]
I've got this same problem on Arch Linux using SDKMAN's java 8 and 11 "-zulu" as with distro java.

**Comment by chemzqm** [comment]
The server unexpected crashed, from coc-java 1.14.0, use `:CocCommand java.open.serverLog` to open log of jdt.ls

Use `"java.jdt.ls.lombokSupport.enabled": false` to disable lombok support.
