### ISSUE TITLE
client start error 

### ISSUE THREAD

**Issue by ancion** [neoclide/coc-java#226]
## versions

vim version: NVIM v0.8.0-1210-gd367ed9b2
node version: v16.18.0
coc.nvim version: 0.0.82-f39f5f69 2022-10-07 23:24:25 +0800
coc.nvim directory: C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim
term: vtpcon
platform: win32

## Log of coc.nvim

2022-10-13T16:20:34.638 INFO (pid:16544) [services] - registered service "languageserver.groovy"
2022-10-13T16:20:34.645 INFO (pid:16544) [services] - LanguageClient groovy state change: stopped => starting
2022-10-13T16:20:34.646 INFO (pid:16544) [services] - registered service "languageserver.lua"
2022-10-13T16:20:34.646 INFO (pid:16544) [services] - registered service "languageserver.golang"
2022-10-13T16:20:34.646 INFO (pid:16544) [services] - registered service "languageserver.bash"
2022-10-13T16:20:34.646 INFO (pid:16544) [services] - registered service "languageserver.ccls"
2022-10-13T16:20:34.646 INFO (pid:16544) [services] - registered service "languageserver.dls"
2022-10-13T16:20:34.713 WARN (pid:16544) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-actions\out\index.js:1:8301)
    at Object.t.activate (C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-actions\out\index.js:1:15288)
2022-10-13T16:20:34.744 INFO (pid:16544) [services] - registered service "diagnostic-languageserver"
2022-10-13T16:20:35.347 INFO (pid:16544) [plugin] - coc.nvim initialized with node: v16.18.0 after 1015ms
2022-10-13T16:20:35.381 INFO (pid:16544) [language-client-index] - Language server "languageserver.groovy" started with 7112
2022-10-13T16:20:35.480 INFO (pid:16544) [attach] - receive notification: highlight []
2022-10-13T16:20:35.501 WARN (pid:16544) [workspace] - workspace.showMessage is deprecated, please use window.showMessage instead. 
    at Object.t.activate (C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-groovy\lib\index.js:1:1755)
    at async C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:255:25881
2022-10-13T16:20:35.581 INFO (pid:16544) [coc-java] - Using java from F:/jdk17, version: 17
2022-10-13T16:20:35.748 INFO (pid:16544) [coc-groovy] - Starting Groovy Language Server with: F:\jdk17\bin\java.exe -Dfile.encoding=utf-8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-groovy\server\groovy-language-server-all.jar
2022-10-13T16:20:35.786 INFO (pid:16544) [extension:coc-java] - Starting Java server with: F:\jdk17\bin\java.exe --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf-8 -DwatchParentProcess=false -javaagent:D:/maven_repository/repo_current/org/projectlombok/lombok/1.18.20/lombok-1.18.22.jar -jar C:\Users\unicorn\AppData\Local\coc\extensions\coc-java-data\server\plugins\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration C:\Users\unicorn\AppData\Local\coc\extensions\coc-java-data\server\config_win -data C:\Users\unicorn\AppData\Local\coc\extensions\coc-java-data\jdt_ws_96210f53de12e0483ec8d7b54d7a8804
2022-10-13T16:20:35.788 INFO (pid:16544) [coc-java] - JDT Language Server starting at d:\GIT\schedule\SpringQuartz
2022-10-13T16:20:35.788 INFO (pid:16544) [services] - registered service "java"
2022-10-13T16:20:35.789 WARN (pid:16544) [workspace] - workspace.showMessage is deprecated, please use window.showMessage instead. 
    at C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-groovy\lib\index.js:1:2246
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-13T16:20:35.797 INFO (pid:16544) [language-client-index] - Language server "java" started with 1080
2022-10-13T16:20:35.806 INFO (pid:16544) [language-client-index] - Language server "groovy" started with 3012
2022-10-13T16:20:35.833 ERROR (pid:16544) [language-client-client] - Server java initialization failed. gg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
    at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
    at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-10-13T16:20:35.835 ERROR (pid:16544) [server] - unhandledRejection  Promise {
  <rejected> gg [Error]: Pending response rejected since connection got disposed
      at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
      at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
      at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
      at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
      at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
      at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
      at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
      at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
      at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
      at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
    code: -32097,
    data: undefined
  }
} gg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
    at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
    at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-10-13T16:20:35.841 INFO (pid:16544) [language-client-index] - Language server "java" started with 6584
2022-10-13T16:20:35.873 ERROR (pid:16544) [language-client-client] - Server java initialization failed. gg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
    at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
    at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-10-13T16:20:35.874 ERROR (pid:16544) [server] - unhandledRejection  Promise {
  <rejected> gg [Error]: Pending response rejected since connection got disposed
      at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
      at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
      at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
      at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
      at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
      at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
      at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
      at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
      at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
      at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
    code: -32097,
    data: undefined
  },
  dispose: [Function (anonymous)]
} gg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
    at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
    at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-10-13T16:20:35.881 INFO (pid:16544) [language-client-index] - Language server "java" started with 16980
2022-10-13T16:20:35.912 ERROR (pid:16544) [language-client-client] - Server java initialization failed. gg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
    at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
    at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-10-13T16:20:35.918 INFO (pid:16544) [language-client-index] - Language server "java" started with 17344
2022-10-13T16:20:35.946 ERROR (pid:16544) [language-client-client] - Server java initialization failed. gg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:50:4562)
    at Object.dispose (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:213:90218)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10821)
    at ad.handleConnectionClosed (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:222:3553)
    at t (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:218:10473)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230)
    at Re (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:24:6501)
    at sk.invoke (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:14460)
    at Rc.fire (C:\Users\unicorn\AppData\Local\nvim\plugged\coc.nvim\build\index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-10-13T16:20:37.627 INFO (pid:16544) [attach] - receive notification: highlight []
2022-10-13T16:20:38.573 INFO (pid:16544) [services] - LanguageClient groovy state change: starting => running
2022-10-13T16:20:38.580 INFO (pid:16544) [services] - service languageserver.groovy started
2022-10-13T16:20:39.328 WARN (pid:16544) [workspace] - workspace.showMessage is deprecated, please use window.showMessage instead. 
    at C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-groovy\lib\index.js:1:2057
2022-10-13T16:20:39.345 WARN (pid:16544) [workspace] - workspace.showMessage is deprecated, please use window.showMessage instead. 
    at y (C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-groovy\lib\index.js:1:121593)
    at async t.getClasspath (C:\Users\unicorn\AppData\Local\coc\extensions\node_modules\coc-groovy\lib\index.js:1:123677)
2022-10-13T16:20:41.660 INFO (pid:16544) [attach] - receive notification: showInfo []

**Comment by rochakgupta** [comment]
+1

Encountering same error.

**Comment by pavva91** [comment]
Same error.

**Comment by pavva91** [comment]
Update to java 17 as in this [issue](https://github.com/neoclide/coc-java/issues/214). Now eclipse.jdt requires 17.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
