### ISSUE TITLE
 _java.reloadBundles.command not found

### ISSUE THREAD

**Issue by sify21** [neoclide/coc-java#227]
After I open a java project, I saw this error in `CocCommand workspace.showOutput`.
```
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[Info  - 4:02:51 PM] JDT Language Server started
[object Object]
[Error - 4:02:52 PM] Oct 24, 2022, 4:02:52 PM org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at org.eclipse.jdt.ls.core.internal.JavaClientConnection.executeClientCommand(JavaClientConnection.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.synchronizeBundles(JDTLanguageServer.java:391)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:288)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:131)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
output from `CocInfo`:
```
## versions

vim version: VIM - Vi IMproved 9.0 9000750
node version: v16.18.0
coc.nvim version: 0.0.82-128edc61 2022-10-23 18:05:21 +0800
coc.nvim directory: /Users/sify21/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2022-10-24T16:02:44.256 INFO (pid:44059) [plugin] - coc.nvim initialized with node: v16.18.0 after 77ms
2022-10-24T16:02:44.601 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:45.114 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:45.532 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:45.970 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:46.441 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:46.804 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:47.147 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:47.505 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:48.796 INFO (pid:44059) [coc-java] - Using java from /Users/sify21/.asdf/installs/java/temurin-17.0.4+101, version: 17
2022-10-24T16:02:48.834 INFO (pid:44059) [extension:coc-java] - Starting Java server with: /Users/sify21/.asdf/installs/java/temurin-17.0.4+101/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf-8 -javaagent:/Users/sify21/.config/coc/extensions/coc-java-data/lombok.jar -jar /Users/sify21/.config/coc/extensions/coc-java-data/server/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /Users/sify21/.config/coc/extensions/coc-java-data/server/config_mac -data /Users/sify21/.config/coc/extensions/coc-java-data/jdt_ws_7cd2f4d330ee5e099aef2b982a9c7849
2022-10-24T16:02:48.837 INFO (pid:44059) [coc-java] - JDT Language Server starting at /Users/sify21/Source/test
2022-10-24T16:02:48.838 INFO (pid:44059) [services] - registered service "java"
2022-10-24T16:02:48.843 INFO (pid:44059) [language-client-index] - Language server "java" started with 44238
2022-10-24T16:02:49.017 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:50.445 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:50.461 INFO (pid:44059) [services] - LanguageClient Language Support for Java state change: starting => running
2022-10-24T16:02:50.948 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:51.348 INFO (pid:44059) [attach] - receive notification: highlight []
2022-10-24T16:02:55.871 INFO (pid:44059) [attach] - receive notification: highlight []
```

**Comment by antonmry** [comment]
I had the same problem. I've tried with the previous version of jdt (1.17.0) instead of 1.18.0 and it worked.

Downloaded https://download.eclipse.org/jdtls/snapshots/jdt-language-server-1.17.0-202210271413.tar.gz

and replaced `~/.config/coc/extensions/coc-java-data/server`

**Comment by dnokov** [comment]
> I had the same problem. I've tried with the previous version of jdt (1.17.0) instead of 1.18.0 and it worked.
> 
> Downloaded https://download.eclipse.org/jdtls/snapshots/jdt-language-server-1.17.0-202210271413.tar.gz
> 
> and replaced `~/.config/coc/extensions/coc-java-data/server`

Cheers, you're a real life saver. 
For any Manjaro users: building version 1.16.0 from AUR does solve the problem, version 17 and 18 have the same issues.

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
