### ISSUE TITLE
Autocomplete issues

### ISSUE THREAD

**Issue by Taz03** [neoclide/coc-java#237]
```
2023-01-29T00:31:43.723 WARN (pid:281966) [completion-complete] - Completion timeout after 5000ms [ [32m'java'[39m ]
```
i dont get any autocomplete suggestions

java 17, gradle project

**Comment by Taz03** [comment]
Autocomplete works fine on other projects its just this one project it is not working partially

by partially i mean
when i do this i get no autocomplete suggestions
![image](https://user-images.githubusercontent.com/73871477/215286358-8ffd90b7-6fb8-4882-887d-3a34c9fffb13.png)

![image](https://user-images.githubusercontent.com/73871477/215286398-0090a4e3-0d6f-4150-861c-e0bf549699c6.png)
but here i do get autocomplete suggestions, so ig its just taking a little long here idk y, maybe increasing timeout will work

**Comment by chemzqm** [comment]
Seems the server not started, try `:CocCommand java.open.output`

**Comment by Taz03** [comment]
> Seems the server not started, try `:CocCommand java.open.output`

i dont think so, how will it work right after it then?

**Comment by Taz03** [comment]
anyways heres the ouput
```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[Info  - 00:02:13.667] JDT Language Server started
{
  javaRequirement: { java_home: '/usr/lib/jvm/java-17-openjdk', java_version: 17 },
  apiVersion: '0.2'
}
[Error - 00:02:19.992] Jan 29, 2023, 12:02:19 AM org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at org.eclipse.jdt.ls.core.internal.JavaClientConnection.executeClientCommand(JavaClientConnection.java:101)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.synchronizeBundles(JDTLanguageServer.java:390)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:285)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/executeClientCommand failed with message: Command: _java.reloadBundles.command not found
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by chemzqm** [comment]
Should be fixed on recent version of coc-java, try upgrade coc.nvim to latest release and coc-java to version 1.14.0.
