### ISSUE TITLE
[coc.nvim]: UnhandledRejection: TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by sify21** [neoclide/coc-java#267]
os
```
Ubuntu 23.04 (Lunar Lobster)
```
:CocInfo
```
## versions

vim version: VIM - Vi IMproved 9.0 9001189
node version: v18.17.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/sify/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-10-13T17:14:08.656 INFO (pid:32982) [plugin] - coc.nvim initialized with node: v18.17.1 after 97
2023-10-13T17:14:08.756 ERROR (pid:32982) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read properties of null (reading '0')
      at lombokPath2Version (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23277:56)
      at lombokPath2VersionNumber (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23281:30)
      at addLombokParam (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23308:35)
      at prepareParams (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23554:5)
      at prepareExecutable (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23478:21)
      at StandardLanguageClient.initialize (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:28729:25)
      at async startStandardServer (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:29671:3)
      at async /home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:29654:9
} TypeError: Cannot read properties of null (reading '0')
    at lombokPath2Version (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23277:56)
    at lombokPath2VersionNumber (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23281:30)
    at addLombokParam (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23308:35)
    at prepareParams (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23554:5)
    at prepareExecutable (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:23478:21)
    at StandardLanguageClient.initialize (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:28729:25)
    at async startStandardServer (/home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:29671:3)
    at async /home/sify/.config/coc/extensions/node_modules/coc-java/lib/index.js:29654:9
```

**Comment by ggascon** [comment]
A workaround is to comment this line:
`"java.jdt.ls.vmargs": "-javaagent:/home/sify/.config/coc-lsp/lombok.jar",`
in coc-settings.json

**Comment by sify21** [comment]
Then how to specify lombok location to coc-java?

**Comment by Henry-Savary-Jackson** [comment]
Try adding the version number of lombok to the actual lombok jar filename. For example changing "lombok.jar" to "lombok-1.18.28.jar". Make sure to follow to format precisely.
Hope this helps! :)

**Comment by w9666** [comment]
> Try adding the version number of lombok to the actual lombok jar filename. For example changing "lombok.jar" to "lombok-1.18.28.jar". Make sure to follow to format precisely. Hope this helps! :)

This is insane. It works.

**Comment by EvandroLG** [comment]
Wow! It worked out! o.O

**Comment by trev-dev** [comment]
This is the *dumbest* problem.  I don't have to do this with other LSP configurations, not sure why it comes up here?

**Comment by trev-dev** [comment]
Hey so easy workaround, set this:   `"java.jdt.ls.lombokSupport.enabled": true` - and remove the javaagent flag from the vmargs.  I don't remember this working well for myself in the past, but it works now.

Also, if you want to use your own version of lombok, this works: https://github.com/neoclide/coc-java/issues/240#issuecomment-1453010150

**Comment by medwards** [comment]
Same as trev-dev, I get this error when my settings are:
```
"java.jdt.ls.lombokSupport.enabled": true,
"java.jdt.ls.vmargs": "-javaagent:/home/medwards/.local/share/lombok/lombok.1.18.24.jar"
```

Disabling Lombok support ends up working fine.

Removing vmargs will not crash the LSP anymore, but it will not process the lombok annotations either - I have to add the lombok jar to `~/.config/coc/extensions/node_modules/coc-java/lombok/`
