### ISSUE TITLE
Error choosing `show errors` action on workspace import

### ISSUE THREAD

**Issue by asmodeus812** [neoclide/coc-java#277]
If we execute `workspace.clean`, and there are errors in the project, we are asked to see the errors, when i select show errors, i get the following error

![image](https://github.com/neoclide/coc-java/assets/15955811/ea1718d5-a0e4-48d8-a429-dad84802edfc)

```
[coc.nvim]: UnhandledRejection: Command: workbench.panel.markers.view.focus not found
Error: Command: workbench.panel.markers.view.focus not found
    at CommandManager.executeCommand (/home/asmodeus/.local/share/nvim/lazy/coc.nvim/build/index.js:27975:17)
    at showImportFinishNotification (/home/asmodeus/.config/coc/extensions/node_modules/coc-java/lib/index.js:29227:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
``

**Comment by xiran56** [comment]
same error
Windows 11
jdk 17 (autoinstalled jre from npm (why?))

**Comment by azat** [comment]
Probably the `release` file is missing, see
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/405#issuecomment-1249082357
- https://github.com/microsoft/vscode-java-debug/issues/1212#issuecomment-1250932155

**Comment by chemzqm** [comment]
Fixed, you use `:CocList diagnostics` for this case
