### ISSUE TITLE
Can not use java.jdt.ls.home

### ISSUE THREAD

**Issue by luizcoro** [neoclide/coc-java#9]
When I set java.jdt.ls.home to a jdtls folder, coc-java gives the following error:

[coc.nvim] JDT Language Server starting at /home/luiz/Documents/learning/java/FirstApp
[coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
[coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
[coc.nvim] Error output from java: Connection to server is erroring. Shutting down server.
[vim-node-coc]: Uncaught exception: TypeError: Cannot convert object to primitive value
    at ChildProcess.client_1.BaseLanguageClient.createMessageTransports.serverProcess.on.code (/snapshot/coc.nvim/lib/language-client/index.js:347:35)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

Steps:
1) install coc-java (:CocInstall coc-java)
2) download the lastest snapshot of jdtls on http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz
3) decompress the tar.gz to a local folder (/home/luiz/jdtls in my case)
4) add java.jdt.ls.home in coc-settings.json ("java.jdt.ls.home" : "/home/luiz/jdtls" in my case)
5) open some java file

**Comment by crr0004** [comment]
You don't have to manually install JDTLS, it is included with the plugin. Is there a reason you're using the latest snapshot of JDTLS?

**Comment by luizcoro** [comment]
My coc-java instalation is using jdtls version 0.29.0.201811280615 while the lastest version is 0.35.0.201903050055. Since I did not figured out how to upgrade coc-java's own jdtls I was trying to keep jdtls up-to-date myself.

I don't know if :CocUpdateSync would upgrade jdtls but in my machine this command gives the following messages:

Error detected while processing function coc#rpc#request[2]..<SNR>35_request:
line    7: connect ETIMEDOUT 192.30.253.117:443

**Comment by chemzqm** [comment]
> I don't know if :CocUpdateSync would upgrade jdtls but in my machine 

It only upgrade itself.

> Error detected while processing function coc#rpc#request[2]..35_request:
line 7: connect ETIMEDOUT 192.30.253.117:443

You have `JDTLS_CLIENT_PORT` in your environment variable, which is used for local language server, but it can't connect to server by use that port.

**Comment by JayceCao** [comment]
The problem still exists in 1.2.0 on my neovim. The error log is:
```
2019-03-20T09:01:55.401 INFO (pid:28853) [services] - registed service "languageserver.MPLS"
2019-03-20T09:01:55.402 INFO (pid:28853) [services] - registed service "languageserver.lua"
2019-03-20T09:01:55.403 INFO (pid:28853) [services] - registed service "languageserver.clangd"
2019-03-20T09:01:55.563 INFO (pid:28853) [services] - registed service "highlight"
2019-03-20T09:01:55.563 INFO (pid:28853) [services] - highlight server state change: stopped => starting
2019-03-20T09:01:55.577 INFO (pid:28853) [plugin] - coc initialized with node: v8.9.0
2019-03-20T09:01:55.628 INFO (pid:28853) [services] - registed service "java"
2019-03-20T09:01:55.734 INFO (pid:28853) [services] - highlight server state change: starting => running
2019-03-20T09:01:55.736 INFO (pid:28853) [services] - service highlight started
2019-03-20T09:01:55.883 ERROR (pid:28853) [language-client-client] - connection error: { Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at Pipe.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } undefined
2019-03-20T09:01:55.885 INFO (pid:28853) [services] - Language Support for Java state change: starting => stopped
2019-03-20T09:01:55.885 ERROR (pid:28853) [language-client-client] - connection error: Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at StreamMessageWriter.write (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/messageWriter.js:69:27)
    at connection.sendRequest.Promise (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:810:35)
    at new Promise (<anonymous>)
    at Object.sendRequest (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:800:26) undefined
2019-03-20T09:01:55.886 ERROR (pid:28853) [language-client-client] - connection error: Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at StreamMessageWriter.write (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/messageWriter.js:71:27)
    at connection.sendRequest.Promise (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:810:35)
    at new Promise (<anonymous>)
    at Object.sendRequest (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:800:26) undefined
2019-03-20T09:01:55.888 ERROR (pid:28853) [server] - uncaughtException TypeError: Cannot convert object to primitive value
    at ChildProcess.client_1.BaseLanguageClient.createMessageTransports.serverProcess.on.code (/snapshot/coc.nvim/lib/language-client/index.js:348:39)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

My config is just as https://github.com/neoclide/coc-java/issues/11#issuecomment-474244105 described.

**Comment by chemzqm** [comment]
The error means connection to server is closed, but I don't know why.

Could you try get the output from language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel?

Or try to use language server downloaded by coc-java instead of use `java.jdt.ls.home`

**Comment by JayceCao** [comment]
> The error means connection to server is closed, but I don't know why.
> 
> Could you try get the output from language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel?
> 
> Or try to use language server downloaded by coc-java instead of use `java.jdt.ls.home`

It's no problem using jdtls downloaded by coc-java. But I found it can't complete third-party libraries. I've no idea whether the problem is jdtls's or coc-java's. I use `eclipse` plugin of gradle to manage dependences.

**Comment by chemzqm** [comment]
https://github.com/redhat-developer/vscode-java/issues/10#issuecomment-268834749

**Comment by JayceCao** [comment]
> [redhat-developer/vscode-java#10 (comment)](https://github.com/redhat-developer/vscode-java/issues/10#issuecomment-268834749)

If I don't understand wrongly, it only supports basic Java gradle applications? My project is just java-application with groovy build script DSL, not Android project.

**Comment by chemzqm** [comment]
I've tested it with sample gradle based project https://github.com/web3j/sample-project-gradle, it works as expected for me, although it takes some time to build the project the first time.

**Comment by chemzqm** [comment]
I thinks the problem is latest jdt.ls doesn't have support for gradle version <= 2.4, you have to upgrade gradle.

Run `:CocList diagnostics` to get the error message.
