### ISSUE TITLE
Package javax.persistence does not exist

### ISSUE THREAD

**Issue by Rheisen** [neoclide/coc-java#94]
I'm trying to use this extension to work with java spring projects, and I'm running into the 'package javax.persistence does not exist' message on all of the imports. The code completion shows everything in the persistence package, so I'm not sure why that is displaying as an error.

Likewise all of the things relying on that package have an error saying it can't find the symbol.

**Comment by chemzqm** [comment]
Read doc of jdt.ls

**Comment by Rheisen** [comment]
From what I've been able to find out, the issue I'm describing seems to exist: [here](https://github.com/eclipse/eclipse.jdt.ls/issues/967)

I've tried the suggestions from that thread and still haven't been able to get this working.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Rheisen** [comment]
```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage
[Warn  - 12:00:51 AM] Jun 13, 2020, 12:00:51 AM While loading class "org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions$LookupStrategy", thread "Thread[Worker-1: Loading available Gradle versions,5,main]" timed out waiting (30034ms) for thread "Thread[Worker-0: Refreshing workspace,5,main]" to finish starting bundle "org.eclipse.buildship.core_3.1.4.v20200211-2258-s [11]". To avoid deadlock, thread "Thread[Worker-1: Loading available Gradle versions,5,main]" is proceeding but "org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions$LookupStrategy" may not be fully initialized.
Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.4.v20200211-2258-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=11] STARTED [STARTED]
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="3.1.4.v20200211-2258-s"; osgi.identity="org.eclipse.buildship.core"; singleton:="true" [id=11] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:350)
	at org.eclipse.osgi.container.Module.start(Module.java:419)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:493)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:571)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:60)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 30 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:347)
	... 11 more
Caused by: org.eclipse.osgi.framework.util.ThreadInfoReport: Thread dump

```

This warning is in the output, would pasting the full output be more useful?
